### ISSUE TITLE
Bower install not working

### ISSUE THREAD

**Issue by anotherwally** [tinacious/toLowerCase#1]
Hello,

I'm trying to update my project and toLowerCase was already installed on another computer, but when I try to update the dependencies on project I'm getting this error:

`bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower toLowerCase#0.0.1      ENOTFOUND Package toLowerCase not found
`

Any thoughts on how can I update the dependencies without getting this error?

**Comment by tinacious** [comment]
Thanks for posting @Warlord08 . I was able to see the message you mentioned but the plugin still installed successfully. 

Nonetheless, I've renamed the Bower package to **angular-tolowercase** to keep inline with Bower's conventions.

Please see the updated README for installation, dependency injection, and demo changes.

**Comment by anotherwally** [comment]
Awesome! Thanks for the update @tinacious
